Update Fees & Gas
SecretFoundation/docs pull request #46
Opened 2022-01-14 19:00 UTC by StoicNorth

Minor copy and grammar updates. @dylanschultzie

2022-01-14 19:04 UTC, dylanschultzie requested changes

2022-01-14 19:04 UTC, dylanschultzie commented on docs/cli/secretcli.md
> +Validator's have a minimum gas price (multi-denom) configuration used to determin if they should include a transaction in a block during `CheckTx`, where `gasPrices >= minGasPrices`.
typo: determin -> determine

2022-01-14 19:04 UTC, dylanschultzie commented on docs/cli/secretcli.md
> +txs by `gasPrice` in the mempool, increaseing tx priority based on fees or gas prices.
typo: increaseing -> increasing

2022-01-17 18:49 UTC, StoicNorth reviewed
Fix typos.

2022-01-17 19:44 UTC, dylanschultzie approved these changes

2022-01-17 19:44 UTC, merged