Update Send Tokens
SecretFoundation/docs pull request #48
Opened 2022-01-14 19:20 UTC by StoicNorth

Make copy more concise. @dylanschultzie

2022-01-14 19:21 UTC, StoicNorth commented on docs/cli/secretcli.md
> -::: warning Note
Is there a reason why this is lowercase? @dylanschultzie

2022-01-14 19:31 UTC, StoicNorth commented on docs/cli/secretcli.md
> -::: warning Note
I answered my own question. Plz ignore the changes to the case for all warning --> Warning changes.

2022-01-15 01:12 UTC, dylanschultzie requested changes

2022-01-15 01:12 UTC, dylanschultzie commented on docs/cli/secretcli.md
> +::: Warning Note
Missed one!

2022-01-17 18:52 UTC, StoicNorth reviewed
Update typo in markup

2022-01-17 18:52 UTC, StoicNorth commented on docs/cli/secretcli.md
> +::: Warning Note
Nice find

2022-01-17 19:46 UTC, merged

2022-01-17 19:46 UTC, dylanschultzie approved these changes