Complete page copy update
SecretFoundation/docs pull request #61
Opened 2022-01-18 18:25 UTC by StoicNorth

Improved copy and page organization to be more user friendly. @dylanschultzie

2022-01-19 02:39 UTC, dylanschultzie requested changes

2022-01-19 02:39 UTC, dylanschultzie commented on docs/protocol/sgx.md
> +- That it's running securely within an enclave on an Intel SGX enabled platform
lowercase `That`

2022-01-20 12:35 UTC, StoicNorth reviewed
Fix typos

2022-01-20 12:35 UTC, StoicNorth commented on docs/protocol/sgx.md
> +- That it's running securely within an enclave on an Intel SGX enabled platform
Fixed.

2022-01-24 18:23 UTC, merged