secret-contract.md test code snippets
SecretFoundation/docs pull request #87
Opened 2022-01-31 15:37 UTC by StoicNorth

Tested code snippets up to 'Simple Counter Project'. Also made minor copy updates. @dylanschultzie

2022-01-31 16:59 UTC, StoicNorth commented
Will make separate commits directly to the phase 2 branch after this PR is accepted @dylanschultzie

2022-01-31 18:40 UTC, StoicNorth commented
Complete working through secret-contracts.md

2022-02-01 16:04 UTC, StoicNorth commented
Updated copy and test code of secret-contracts.md and privacy-model-of-secret-contracts.md @dylanschultzie

2022-02-10 00:48 UTC, dylanschultzie requested changes

2022-02-10 00:48 UTC, dylanschultzie commented on docs/dev/privacy-model-of-secret-contracts.md
> -```rust
we do want these in here - it's what gives it the formatting.

2022-02-10 00:48 UTC, dylanschultzie commented on docs/dev/privacy-model-of-secret-contracts.md
> -```rust
and here

2022-02-10 00:48 UTC, dylanschultzie commented on docs/dev/privacy-model-of-secret-contracts.md
> -```rust
and here

2022-02-10 00:48 UTC, dylanschultzie commented on docs/dev/privacy-model-of-secret-contracts.md
> -```rust
and here

2022-02-10 00:48 UTC, dylanschultzie commented on docs/dev/privacy-model-of-secret-contracts.md
> -```rust
and here

2022-02-10 00:48 UTC, dylanschultzie commented on docs/dev/privacy-model-of-secret-contracts.md
> -```rust
(and more further down, but I'll stop here)

2022-02-11 14:51 UTC, StoicNorth reviewed
Fixed formatting

2022-02-11 15:41 UTC, dylanschultzie commented on docs/dev/privacy-model-of-secret-contracts.md
> +```rustrust
typo.

there's got to be some way that I can simply go in and fix these small errors.

2022-02-11 18:46 UTC, merged